### ISSUE TITLE
use python.exe to launch stopgo on windows

### ISSUE THREAD

**Issue by notklaatu** [notklaatu/stopgo#19]
On Windows 7 and 10 (at  least), stopgo fails to launch. Doesn't know what to use to launch it.

User reporting issue does not know how to associate Stopgo with Python.exe so we need to do this automagically for them at install time. Apparently this entails a registry entry. No idea how to do that, but I'll investigate.

**Comment by notklaatu** [comment]
might be using cx_freeze to fix this. initial tests are good; hopefully i'll be able to package it up correctly with NSIS.

**Comment by notklaatu** [comment]
fixed 266d39f

Still needs external testing by user, but closing for now since I don't see any WAITING status in github issue tracker..

**Comment by cyanidecupcake** [comment]
Error on install for fully updated Windows 10.  (Reported by Debbie) 
![windowserror](https://cloud.githubusercontent.com/assets/13429860/15842438/2a6480de-2cad-11e6-9182-7d8da8e9d90e.jpg)

**Comment by cyanidecupcake** [comment]
Same error on install for Windows 7.  (Reported by Matt)
![maker box error mesage](https://cloud.githubusercontent.com/assets/13429860/15910044/49409760-2e1d-11e6-8040-ab320414226b.PNG)

**Comment by notklaatu** [comment]
OK, looks like this actually has to do with how windows sets its PATH env var (or rather, does not). Working on a fix now.

Also, how did people develop before the days of [Qemu](http://qemu.org)? seriously. How.

**Comment by notklaatu** [comment]
[RESOLVED] [WAITING FOR CONFIRMATION]
commit 571b88e

with a combination of WinFF for a friendly FFmpeg install, NSIS path settings with EnvVarUpdates.nsh, I believe this issue is now fixed. Just to make sure all these pieces fall into the right places, @cyanidecupcake is posting an install instruction page (3 easy steps) at Makerbox.org.nz/stopgo

**Comment by notklaatu** [comment]
From http://nsis.sourceforge.net/Docs/Chapter4.html

The program files directory (usually C:\Program Files but detected at runtime). On Windows x64, $PROGRAMFILES and $PROGRAMFILES32 point to C:\Program Files (x86) while $PROGRAMFILES64 points to C:\Program Files. Use $PROGRAMFILES64 when installing x64 applications.

**Comment by cyanidecupcake** [comment]
Patch worked for Debbie (mentioned above, Windows 10) and the user who first reported the error (two Windows 10 machines).

Patch did not work for beta-tester Tim who still received the same error.

Sam was able to install on Windows 7 with no issue.
Patrick received the usual error message on Windows 10.

**Comment by cyanidecupcake** [comment]
Adam received a new error message saying:

"I already had VLC Installed so I started step two. I didn't change any options off default and just kept clicking through. I ran both installers from within the archive and then ditched them. WinFF starts up at the end of the dependency install on default route, might want to be careful of people who think that's StopGo?"

![abbmbdi](https://cloud.githubusercontent.com/assets/13429860/16284265/7d0c3f92-3924-11e6-9b37-777a6eaf30f3.png)

**Comment by titimoby** [comment]
by default, the dependencies installer install python 2.7 (is it 2017? ;)) but in the setup, default settings doesn't add python.exe to the path.
It may be the issue?

Edit: false. I just installed everything with default settings on Win10 and StopGo launched.
